### ISSUE TITLE
Improve repo readme

### ISSUE THREAD

**Issue by jatkinson1000** [Cambridge-ICCS/rse-skills-python#5]
Add longer description, general tidying for summer school applicability.

**Comment by jatkinson1000** [comment]
Slides for the workshop can be found at https://cambridge-iccs.github.io/rse-skills-python

These can be linked from the README (and perhaps the slides?).

**Comment by MarionBWeinzierl** [comment]
> Slides for the workshop can be found at https://cambridge-iccs.github.io/rse-skills-python
> 
> These can be linked from the README (and perhaps the slides?).

I added it to the README.
